#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
# List of local libraries


# Path to the current BSP
SEARCH_TARGET_APP_CY8CKIT-062S2-43012=bsps/TARGET_APP_CY8CKIT-062S2-43012

# The search paths for the included middleware
SEARCH_freertos=../mtb_shared/freertos/release-v10.4.302
SEARCH_ml-inference=../mtb_shared/ml-inference/release-v2.0.0
SEARCH_ml-middleware=../mtb_shared/ml-middleware/release-v2.0.1
SEARCH_ml-tflite-micro=../mtb_shared/ml-tflite-micro/release-v2.0.0
SEARCH_retarget-io=../mtb_shared/retarget-io/release-v1.5.0
SEARCH_sensor-motion-bmi160=../mtb_shared/sensor-motion-bmi160/release-v1.1.2
SEARCH_sensor-orientation-bmx160=../mtb_shared/sensor-orientation-bmx160/release-v1.0.2
SEARCH_abstraction-rtos=../mtb_shared/abstraction-rtos/release-v1.7.4
SEARCH_BMI160_driver=../mtb_shared/BMI160_driver/bmi160_v3.9.1
SEARCH_BMM150-Sensor-API=../mtb_shared/BMM150-Sensor-API/bmm150_v2.0.0
SEARCH_cat1cm0p=../mtb_shared/cat1cm0p/release-v1.2.0
SEARCH_clib-support=../mtb_shared/clib-support/release-v1.4.2
SEARCH_cmsis=../mtb_shared/cmsis/release-v5.8.0
SEARCH_core-lib=../mtb_shared/core-lib/release-v1.4.1
SEARCH_core-make=../mtb_shared/core-make/release-v3.2.2
SEARCH_mtb-hal-cat1=../mtb_shared/mtb-hal-cat1/release-v2.4.3
SEARCH_mtb-pdl-cat1=../mtb_shared/mtb-pdl-cat1/release-v3.7.0
SEARCH_recipe-make-cat1a=../mtb_shared/recipe-make-cat1a/release-v2.1.1

# Search libraries added to build
SEARCH_MTB_MK+=$(SEARCH_freertos)
SEARCH_MTB_MK+=$(SEARCH_ml-inference)
SEARCH_MTB_MK+=$(SEARCH_ml-middleware)
SEARCH_MTB_MK+=$(SEARCH_ml-tflite-micro)
SEARCH_MTB_MK+=$(SEARCH_retarget-io)
SEARCH_MTB_MK+=$(SEARCH_sensor-motion-bmi160)
SEARCH_MTB_MK+=$(SEARCH_sensor-orientation-bmx160)
SEARCH_MTB_MK+=$(SEARCH_abstraction-rtos)
SEARCH_MTB_MK+=$(SEARCH_BMI160_driver)
SEARCH_MTB_MK+=$(SEARCH_BMM150-Sensor-API)
SEARCH_MTB_MK+=$(SEARCH_cat1cm0p)
SEARCH_MTB_MK+=$(SEARCH_clib-support)
SEARCH_MTB_MK+=$(SEARCH_cmsis)
SEARCH_MTB_MK+=$(SEARCH_core-lib)
SEARCH_MTB_MK+=$(SEARCH_core-make)
SEARCH_MTB_MK+=$(SEARCH_mtb-hal-cat1)
SEARCH_MTB_MK+=$(SEARCH_mtb-pdl-cat1)
SEARCH_MTB_MK+=$(SEARCH_recipe-make-cat1a)

-include $(CY_INTERNAL_APP_PATH)/importedbsp.mk
COMPONENTS += MW_FREERTOS
COMPONENTS += MW_ML_INFERENCE
COMPONENTS += MW_ML_MIDDLEWARE
COMPONENTS += MW_ML_TFLITE_MICRO
COMPONENTS += MW_RETARGET_IO
COMPONENTS += MW_SENSOR_MOTION_BMI160
COMPONENTS += MW_SENSOR_ORIENTATION_BMX160
COMPONENTS += MW_ABSTRACTION_RTOS
COMPONENTS += MW_BMI160_DRIVER
COMPONENTS += MW_BMM150_SENSOR_API
COMPONENTS += MW_CAT1CM0P
COMPONENTS += MW_CLIB_SUPPORT
COMPONENTS += MW_CMSIS
COMPONENTS += MW_CORE_LIB
COMPONENTS += MW_CORE_MAKE
COMPONENTS += MW_MTB_HAL_CAT1
COMPONENTS += MW_MTB_PDL_CAT1
COMPONENTS += MW_RECIPE_MAKE_CAT1A

# Register map file
DEVICE_CY8C624ABZI-S2D44_SVD=$(SEARCH_mtb-pdl-cat1)/devices/COMPONENT_CAT1A/svd/psoc6_02.svd


#
# generate make targets for the graphical editors that are specific to this project
#

modlibs:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name library-manager
.PHONY: modlibs

library-manager:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name library-manager
.PHONY: library-manager

qspi-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name qspi-configurator
.PHONY: qspi-configurator

config:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name device-configurator
.PHONY: config

device-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name device-configurator
.PHONY: device-configurator

capsense-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name capsense-configurator
.PHONY: capsense-configurator

capsense-tuner:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name capsense-tuner
.PHONY: capsense-tuner

seglcd-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name seglcd-configurator
.PHONY: seglcd-configurator

bsp-assistant:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name bsp-assistant
.PHONY: bsp-assistant

config_bt:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name bt-configurator
.PHONY: config_bt

bt-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name bt-configurator
.PHONY: bt-configurator

config_usbdev:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name usbdev-configurator
.PHONY: config_usbdev

usbdev-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name usbdev-configurator
.PHONY: usbdev-configurator

smartio-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name smartio-configurator
.PHONY: smartio-configurator

config_lin:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name lin-configurator
.PHONY: config_lin

lin-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name lin-configurator
.PHONY: lin-configurator

config_ml:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name ml-configurator
.PHONY: config_ml

ml-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name ml-configurator
.PHONY: ml-configurator

